name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Assembling app debug flavor
        run: ./gradlew :app:assembleDebug
      - name: run java unit tests
        run: ./gradlew test